# Generated by Django 6.0 on 2026-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_password_alter_employee_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='document',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='video',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profiles/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='N/A', max_length=128),
        ),
    ]
