# Generated by Django 6.0 on 2026-01-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_employee_document_remove_employee_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('password', models.CharField(default='N/A', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='audio',
            field=models.FileField(default='N/A', null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(default='N/A', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(default='N/A', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='N/A', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
