# Generated by Django 6.0 on 2026-01-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_department_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee1',
            name='Department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee1',
            name='d_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee1',
            name='d_des',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
