# Generated by Django 6.0 on 2026-01-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee1_department_employee1_d_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee1',
            old_name='Department',
            new_name='department',
        ),
    ]
