# Generated by Django 6.0 on 2026-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='solution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
