# Generated by Django 6.0 on 2026-01-16 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_query_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='name',
            field=models.CharField(error_messages='Entre validate name', max_length=100, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
