# Generated by Django 6.0 on 2026-01-16 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_employee1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='name',
            field=models.CharField(error_messages={'blank': 'Enter a valid name', 'max_length': 'Name must not exceed 10 characters', 'min_length': 'Name must be at least 3 characters'}, max_length=100, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
