# Generated by Django 6.0 on 2026-01-17 06:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_employee1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='contact',
            field=models.CharField(max_length=15, validators=[app.models.Emp1_contact]),
        ),
    ]
